apiVersion: apps/v1
   
kind: Deployment

# for load-balancer  
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
   
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
   
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
   
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
   


# for Nginx
metadata:

  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
